name: event_plus
description: EventPulse is your all-in-one solution for managing event attendees. Effortlessly scan, print badges, and register participants for workshops with a single tool
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # Dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.0

  # Dart functional programming
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1


  # Scan QR code helper
  qr_code_scanner: ^1.0.1


  equatable: ^2.0.5
  http: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  injectable_generator:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  freezed: ^2.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
